language: ruby
sudo: false
cache: bundler
rvm:
  - ruby-head
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.8
os:
  - linux
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
env:
  global:
    - TEST=true
    - CODECLIMATE_REPO_TOKEN=81787f7b1c3bfa937edadcafbc94f807bf5af5c1142c7b793f2d9969a271de1f
script: bundle exec rake test
notifications:
  slack: middleman:JW9OvXmn1m3XrSERe8866nBR
