language: ruby
rvm:
  - ruby-head
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-19mode
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.1.0
    - rvm: jruby-19mode
env: TEST=true
before_install: git submodule update --init --recursive
script: bundle exec rake test