language: ruby
cache: bundler
bundler_args: --without development
before_install: git submodule update --init --recursive
rvm:
  - ruby-head
  - jruby-19mode
  - 2.1.2
  - 2.1.1
  - 2.1.0
  - 2.0.0
  - 1.9.3
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
env: TEST=true CODECLIMATE_REPO_TOKEN=81787f7b1c3bfa937edadcafbc94f807bf5af5c1142c7b793f2d9969a271de1f 
script: bundle exec rake test
notifications:
  slack: middleman:JW9OvXmn1m3XrSERe8866nBR
