language: ruby
cache: bundler
env: TEST=true
bundler_args: --without development
before_install: git submodule update --init --recursive
rvm:
  - ruby-head
  - ruby
  - jruby-head
  - jruby
  - jruby-19mode
  - 2.1.1
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - rbx-2
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: ruby
    - rvm: jruby-head
    - rvm: jruby
    - rvm: jruby-19mode
    - rvm: rbx-2
